packages:
  - build-essential
  - libssl-dev
  - llvm
  - python3-pip
  - python-is-python3
  - vim
  - less

brew:
  taps:
    - aws/tap
    - carlocab/personal
    - homebrew/bundle
    - homebrew/cask
    - homebrew/cask-fonts
    - homebrew/core
    - cloudflare/cloudflare
  casks:
    - 1password
    - alacritty
    - alt-tab
    - aws-vault
    - brave-browser
    - cloudflare/cloudflare/cf-terraforming
    - font-fira-code-nerd-font
    - hiddenbar
    - kdiff3
    - multipass
    - rectangle
    - slack
    - telegram
    - tunnelblick
  packages:
    common:
      - asciinema
      - asdf
      - autoconf
      - automake
      - awscli
      - azure-cli
      - bat
      - codespell
      - coreutils
      - direnv
      - dos2unix
      - dust
      - exa
      - fd
      - fzf
      - gh
      - ghq
      - git-delta
      - hadolint
      - highlight
      - jq
      - jsonnet
      - k9s
      - kustomize
      - lazygit
      - lua-language-server
      - p7zip
      - packer
      - pkg-config
      - pre-commit
      - python-yq
      - ripgrep
      - sponge
      - terraform-docs
      - tflint
      - tfsec
      - tldr
      - tre-command
      - tree
      - tree-sitter
      - yamllint
      - zoxide
    darwin:
      - carlocab/personal/unrar
      - dockutil
      - switchaudio-osx
      - ffmpeg
      - gawk
      - gnu-getopt
      - gnu-sed
      - watch
      - wget
      - xz
    linux: []
  packages_from_source:
    - duf

dotfiles:
  repo: 'https://github.com/shmileee/dotfiles'
  branch: 'master'

neovim:
  build_from_source: false
  directory: "{{ ansible_user_dir }}/Development/repository/github.com/neovim/neovim"
  build_dependencies:
    - autoconf
    - automake
    - cmake
    - curl
    - doxygen
    - g++
    - gettext
    - libtool
    - libtool-bin
    - ninja-build
    - pkg-config
    - unzip

asdf_version: "v0.12.0"
asdf_plugins:
  - name: "python"
    repository: "https://github.com/danhper/asdf-python"
    versions:
      - 3.10.1
    delete_versions: []
    global: system

  - name: "golang"
    repository: "https://github.com/kennyp/asdf-golang"
    versions:
      - 1.18
    delete_versions: []
    global: system

  - name: "ruby"
    repository: "https://github.com/asdf-vm/asdf-ruby"
    versions:
      - 3.0.3
    delete_versions: []
    global: system

  - name: "nodejs"
    repository: "https://github.com/asdf-vm/asdf-nodejs"
    versions:
      - 17.7.2
    delete_versions: []
    global: system

  - name: "terraform"
    repository: "https://github.com/asdf-community/asdf-hashicorp"
    versions:
      - 1.1.7
    delete_versions: []
    global: 1.1.7

  - name: "terraform-ls"
    repository: "https://github.com/shihanng/asdf-terraform-ls"
    versions:
      - 0.26.0
    delete_versions: []
    global: 0.26.0

  - name: "kubectl"
    repository: "https://github.com/asdf-community/asdf-kubectl"
    versions:
      - 1.23.0
    delete_versions: []
    global: 1.23.0

  - name: "helm"
    repository: "https://github.com/Antiarchitect/asdf-helm"
    versions:
      - 3.8.1
    delete_versions: []
    global: 3.8.1

golang:
  path: '{{ ansible_user_dir }}/.go'
  packages:
    - golang.org/x/tools/gopls@latest

nodejs:
  packages:
    - yarn

dockitems_disabled:
  - App Store
  - Contacts
  - FaceTime
  - Launchpad
  - Mail
  - Maps
  - Messages
  - Notes
  - Photos
  - Reminders
  - Safari
  - Terminal
  - iBooks
  - iTunes

dockitems_enabled:
  - name: Brave Browser
    path: "/Applications/Brave Browser.app"
    pos: 1
  - name: Alacritty
    path: "/Applications/Alacritty.app"
    pos: 2
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 3
  - name: Telegram
    path: "/Applications/Telegram.app"
    pos: 4
  - name: Spotify
    path: "/Applications/Spotify.app"
    pos: 5

darwin_hotkeys:
  # remap "show spotlight search` to `⌘ + g`
  64:
    parameters: "103, 5, 1048576"
    enabled: 1
  # disable "select the previous source in input menu"
  60:
    parameters: "32, 49, 262144"
    enabled: 0
  # remap "select the next source in input menu" to `⌘ + space`
  61:
    parameters: "32, 49, 1048576"
    enabled: 1
