#!/usr/bin/env bash

{{ template "common" }}


if [[ ! "$LOGNAME" =~ ^[a-zA-Z0-9][a-zA-Z0-9_-]*$ ]]; then
  echo "Error: LOGNAME contains invalid characters."
  exit 1
fi
if ! sudo -nv > /dev/null 2>&1 ;then
  echo "Please provide your sudo password:"
  sudo -v
fi
# Keep-alive: update existing sudo time stamp until the script has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
# Do we need to ask for sudo password or is it already passwordless?
if ! sudo grep -q 'NOPASSWD:     ALL' /etc/sudoers.d/$LOGNAME > /dev/null 2>&1 ;then
  echo "no sudoer file"

  bot "Enabling passwordless sudo can reduce security. Are you sure you want to proceed?"

  read -r -p "Make sudo passwordless? [y/N] " -n 1 answer
  echo

  if [[ $answer =~ ^[Yy]$ ]];then
    if [ "$(uname)" = "Darwin" ]; then
      if ! sudo grep -q "#includedir /private/etc/sudoers.d" /etc/sudoers; then
        echo '#includedir /private/etc/sudoers.d' | sudo tee -a /etc/sudoers > /dev/null
      fi
      [ ! -d "/private/etc/sudoers.d" ] && sudo mkdir /private/etc/sudoers.d
      TMPFILE=$(mktemp)
      echo -e "Defaults:$LOGNAME    !requiretty\n$LOGNAME ALL=(ALL) NOPASSWD:     ALL" > "$TMPFILE"
      sudo visudo -cf "$TMPFILE" && sudo mv "$TMPFILE" /private/etc/sudoers.d/$LOGNAME || { echo "Error in sudoers file"; rm "$TMPFILE"; exit 1; }
      echo "You can now run sudo commands without password!"
    else
      if ! sudo grep -q "@includedir /etc/sudoers.d" /etc/sudoers; then
        echo '@includedir /etc/sudoers.d' | sudo tee -a /etc/sudoers > /dev/null
      fi
      echo -e "Defaults:$LOGNAME    !requiretty\n$LOGNAME ALL=(ALL) NOPASSWD:     ALL" | sudo tee /etc/sudoers.d/$LOGNAME
      echo "You can now run sudo commands without password!"
    fi
  fi
fi

