export EDITOR=vim
export PATH=$HOME/.local/bin:$PATH
export VISUAL=vim
export ASDF_DIR=/opt/asdf-vm/
export DOTFILES=$HOME/.dotfiles

ANTIGEN_PATH=$HOME/.dotfiles
ZSH_TMUX_AUTOSTART=true

source $ANTIGEN_PATH/antigen/antigen.zsh

# Initialize antigen
antigen init $HOME/.antigenrc

typeset -g -A key

# Set UP and DOWN keys to navigate history

key[Up]="${terminfo[kcuu1]}"
key[Down]="${terminfo[kcud1]}"

[[ -n "${key[Up]}"   ]] && bindkey -- "${key[Up]}"   history-substring-search-up
[[ -n "${key[Down]}" ]] && bindkey -- "${key[Down]}" history-substring-search-down

. /opt/asdf-vm/asdf.sh
fpath=(${ASDF_DIR}/completions $fpath)
autoload -Uz compinit
compinit

eval "$(starship init zsh)"
