---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: default_ubuntu_22
    image: ubuntu:22.04

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"

verifier:
  name: ansible