#!/usr/bin/env bash

# Start script - promts the user to initiate installation and link dotfiles

set -e
trap on_error SIGTERM

source ./scripts/lib/echoes.sh

on_start() {

  source ./bin/dotfile

  bot "This script will guide you through the dofiles setup as well as installing required system packages."
  echo "It will not install anything without your direct agreement!"
  echo
  read -p "Do you want to proceed with the installation? [y/N] " -n 1 answer
  echo
  if [[ ! $answer =~ (yes|y|Y) ]];then
    exit 1
  fi
}

link_dotfiles() {
  bot "Linking dotfiles to the home folder."
  echo
  read -p "Proceed? [y/N] " -n 1 answer
  echo
  if [[ ! $answer =~ (yes|y|Y) ]];then
    exit 1
  fi
  curl -L git.io/antigen > $HOME/antigen.zsh
}

main() {
  on_start "$*"
}

main "$*"
