name: Chezmoi Setup Validation

on:
  push:
    branches:
      - '*'

jobs:
  validate-chezmoi-setup:
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Initialize chezmoi with the current branch content
        run: sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply https://github.com/${{ github.repository }}/tree/${{ steps.extract_branch.outputs.branch }}
